### ISSUE TITLE
Persistent config

### ISSUE THREAD

**Issue by SeNeO** [realies/soulseek-docker#1]
Hi,

I'm trying your docker on unraid and everything seems to work fine. Except that the config is not persisted even with -v "/persistent/appdata":"/root/.SoulseekQt". After rebooting the container I need to log again and modify the options to my liking.
Downloads and log directory are worklng fine.

Am I missing something?

**Comment by realies** [comment]
It seems that Soulseek does not save its configuration on change but on a set interval of time or upon an exit signal by the user which is not available through this container.

Can you try setting the "Save client data every x minutes" in Options > General to a lower value and checking if the configuration data has been saved to the data persistence folder after the time expires?

**Comment by SeNeO** [comment]
I'm dumb. I had the same issue when I installed soulseek on my computer....
