### ISSUE TITLE
Synology Folder Permissions Reset

### ISSUE THREAD

**Issue by mixm1xmix** [realies/soulseek-docker#100]
I've noticed from time to time the Soulseek folder I have mapped in my Synology has its permissions reset - the Everyone and users groups reset to Read only, preventing me from editing the downloaded files. I think this occurs when the container restarts, as I noticed it today and it had restarted 3 hours ago.

![10-25-24-hobbes - Synology DiskStation_—_Mozilla_Firefox-NEGL6](https://github.com/user-attachments/assets/77b752e3-764c-4ec1-91b8-e5d762777e87)

**Comment by realies** [comment]
https://github.com/realies/soulseek-docker/issues/91#issuecomment-2436527940
