### ISSUE TITLE
How to set password

### ISSUE THREAD

**Issue by ledyx** [realies/soulseek-docker#11]
I wanna add user authentication information.
How should I do that?

**Comment by realies** [comment]
A reverse proxy server with authentication that exposes the container is the common approach at the moment.

**Comment by ledyx** [comment]
Thanks for reply!

**Comment by realies** [comment]
@ledyx, there's a nginx reverse proxy example config provided here, https://github.com/realies/soulseek-docker/blob/master/soulseek.conf, it can be combined with http basic authentication as explained here https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
