### ISSUE TITLE
Feature: resize according to browser window

### ISSUE THREAD

**Issue by MattyBalaam** [realies/soulseek-docker#16]
I was wondering if there could be a way to resize the app according to the browser window?

On a related issue I can’t seem to alter the size after creating the container either, is this currently possible?

**Comment by realies** [comment]
@MattyBalaam, the default mode is to resize the noVNC viewport to the browser dimensions. If you mean the app resolution, this has to be set during container creation time using the `resolution` variable - please check https://github.com/realies/soulseek-docker#using-docker-cli or the compose file.

**Comment by MattyBalaam** [comment]
Yes, to clarify I was wondering if there would be anyway of implementing a set/resize of the app resolution based on the current browser window.

…I guess things could be hairy if more than one window was accessing the client!

**Comment by realies** [comment]
There's no way of signaling and reloading the graphical environment based on a client browser view-port at the moment unfortunately. If it ever becomes a feature of noVNC, we can look into adding it.

**Comment by CKraft11** [comment]
Yeah if there is anyway to eliminate letterboxing in the web ui that would be amazing! Great container keep it up!

**Comment by MattyBalaam** [comment]
Works great 💪
