### ISSUE TITLE
noVNC encountered an error - SyntaxError: The requested module './util/browser.js' does not provide an export named 'supportsImageMetadata'

### ISSUE THREAD

**Issue by ripclaw786** [realies/soulseek-docker#18]
Hi realies

I'm running SoulSeek via a Docker container on my Synology DiskStation DSM3617xs.  SoulSeek was working fine for me about 1 month back and I recently ran into the error in the attached screenshot when trying to launch it in my web browser.

![Screenshot 2020-02-24 at 20 54 45](https://user-images.githubusercontent.com/41956813/75182014-2e0bab80-5748-11ea-9d9b-8d1e35cc7015.png)

I've restarted the container a number of times, without any success.  I've even recreated the container, with the same result.  I then deleted the container and image and recreated the container from scatch and still no joy.  Can you please help?

Thanks.

**Comment by BudSpencer20** [comment]
Try deleting your cookies (the ones related to soulseek-docker), clear browser cache etc. or perhaps try it in Incognito Mode etc.

**Comment by ripclaw786** [comment]
Thanks for this!  All sorted and working now.
