### ISSUE TITLE
.SoulseekQt folder not being populated

### ISSUE THREAD

**Issue by HeadcaseFargone** [realies/soulseek-docker#19]
Using the below volumes none of my settings persist through restarts.  Executing a bash shell in the Soulseek container shows /data/.SoulseekQt to be empty, and only a short .conf file in /data/.config.  I have to enter my username/password and change all my settings every time the container is restarted.  This didn't happen before on a previous version when the volumes pointed to /root/.SoulseekQt instead of /data/.SoulseekQt.  Is this an issue with the newer version or am I doing something wrong?

Edit: Looks like it defaults to 60 minutes before saving config.

    volumes:
     - /Docker/soulseek:/data/.SoulseekQt
     - /media/Downloads:/data/Soulseek Downloads

**Comment by apetresc** [comment]
For what it's worth, you _can_ change the 60 minutes to some other quantity in the `General` settings tab. But it is definitely annoying that the config file isn't saved at least on exit.

**Comment by HeadcaseFargone** [comment]
Hah yeah, figured this one out (and edited the issue) when I found that
setting. I had been restarting Docker too often for it to ever hit 60
minutes.

Really cool Docker image, by the way.

**Comment by realies** [comment]
Does it work as expected after the config save timeout?

**Comment by HeadcaseFargone** [comment]
Yes, working as expected now. Thanks.
