### ISSUE TITLE
"File not shared" but can be browsed

### ISSUE THREAD

**Issue by pblsnchz** [realies/soulseek-docker#20]
I'm facing this strange issue. I setup a folder to share and make it accessible to everyone. I (and other slsk users) can browse this files. However, when attempting to download any file or folder, "File not shared" pops up and obviously nothing is downloaded.
Please advise on how to deal with this issue. I'm running latest version from a docker-compose file, which I can make available if needed.

Thanks for the great job!

**Comment by realies** [comment]
Could not replicate, assuming it would be due to network routing issues.

**Comment by SammyVincent-Dasion** [comment]
Funny, I'm also getting the same error. Also in compose ...
