### ISSUE TITLE
chown: cannot access '/data/*': No such file or directory

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [realies/soulseek-docker#22]
Sorry for what is probably a silly question but I'm new to containers. I have a new Qnap TS653-D Nas and I am trying to create this container via both the Qnap Container Station UI and also via the Docker CLI over SSH.

I took the commands from the code page and made the required changes to the volume mounting to point to the correct folders, as below:

docker run -d --name soulseek --restart=always \
-v "/persistent/appdata":"/Container/container-station-data/application" \
-v "/persistent/downloads":"/Downloads/SoulSeek" \
-v "/persistent/logs":"/Container/container-station-data/application/logs" \
-e pgid=1000 \
-e puid=1000 \
-e resize=scale \
-e resolution=3840x2160 \
-p 9090:9090 \
realies/soulseek

When I try to run the container I get the below response and the container fails to shart.

**chown: cannot access '/data/*': No such file or directory**

The only reference to a data fodler I can see is from the XDG_RUNTIME_DIR environment variable which is set to /data

Any help would be appreciated.

**Comment by BudSpencer20** [comment]
-v "/persistent/appdata":"/Container/container-station-data/application"
-v "/persistent/downloads":"/Downloads/SoulSeek"
-v "/persistent/logs":"/Container/container-station-data/application/logs"

Are these your working folders? The second part in the -v argument should always be the same no matter where its run. In your case your -v argument should be:

-v "**/Container/container-station-data/application**":"/data/.SoulseekQt" \
-v "**/Downloads/SoulSeek**":"/data/Soulseek Downloads" \
-v "**/Container/container-station-data/application/logs**":"/data/Soulseek Chat Logs" \

Try running with the above and see if the container runs successfully. Remember that the user that the container is run as should always have read/write access to the folder on the host system.

**Comment by realies** [comment]
This would be due to incorrect volume mapping, @BudSpencer20 explains that well, more info is available on https://docs.docker.com/storage/volumes/
