### ISSUE TITLE
PUID and PGID parameters

### ISSUE THREAD

**Issue by HeadcaseFargone** [realies/soulseek-docker#24]
I have a local user with uid and gid 1000.  In my docker-compose file I'm passing the parameters PUID=1000 and PGID=1000, yet Soulseek still creates new files and folders as root user.  Other containers that take these same parameters are working properly regarding permissions.  Am I missing something else or is it an issue with this image?

**Comment by realies** [comment]
try using lower case variable names, as defined in the readme

**Comment by HeadcaseFargone** [comment]
That did it.  Thanks for the super quick response.

**Comment by realies** [comment]
@HeadcaseFargone, decided to make these capitalised, so it follows the standard convention seen in other containers :)
