### ISSUE TITLE
Uploads not working and can't be browsed or browse.

### ISSUE THREAD

**Issue by Eowys** [realies/soulseek-docker#26]
So Soulseek works fine, except nobody can download from me nor directly browse my files (I have 200k files so stuff is pretty much always being downloaded from me nearly constantly).
Have manually set ports on my router as well as DS918 NAS but still no joy.
Mounted volumes seem to be working - can add and scan the share fine.
Also can't seem to browse any other users. 
I can download files that I search for using the search function though.

Loading up soulseek on my PC and everything works fine on that end and people start downloading from me almost straight away and I can browse everyone but for some reason it's just not working on my NAS?

**Comment by Eowys** [comment]
Also if I import my client data from my PC client into the container i get all the queued downloads but nothing actually happens. Downloads will only work if I search for a file then download it manually.

**Comment by uoziod** [comment]
Experiencing same issue with Synology NAS

**Comment by realies** [comment]
I don't have a Synology and am unable to replicate the behaviour elsewhere. There's someone else that reported similar behaviour in #23. Since you've mentioned port config is OK, could it be anything to do with permissions?

**Comment by realies** [comment]
@Eowys, @uoziod, does the solution mentioned in #27 work for you?

**Comment by Eowys** [comment]
I'm not sure how to use the commands in that thread? Do I enter them into the terminal in the docker? I'm a bit of a noob when it comes to ssh and commands and stuff - never used them?
I've tried setting permissions in the DS918+ NAS settings as far as I can do but still no joy.

**Comment by realies** [comment]
Please look up how to use these commands through a terminal on your server.
