### ISSUE TITLE
Browser shortcuts interfering with text input

### ISSUE THREAD

**Issue by jt196** [realies/soulseek-docker#28]
I've got a bunch of extensions on my browser (Edge), Vimium amongst them. Tried typing my user name into the Soulseek field - and it's not working. Some keys are, some aren't. Tested this on Safari and it works fine. 

I can only assume that the text entry fields aren't 'switching off' the browser shortcuts.

**Comment by realies** [comment]
It's possible to leave text fields in an unexpected state which may prevent typing text, although it seems to work fine with all major browsers I've tried so far. I believe pressing `alt` may reset bugged states, if we're referring to the same issue.

**Comment by jt196** [comment]
As suspected - it was Vimium C extension interfering with the keyboard input. Switched it off and it's working fine now.

**Comment by realies** [comment]
@jt196 for compatibility with this you may want to either refer to Vimium C or noVNC's developers.
