### ISSUE TITLE
Please rebuild the image with noVNC 1.2.0

### ISSUE THREAD

**Issue by weendigo** [realies/soulseek-docker#30]
Hi,

[noVNC 1.2.0](https://github.com/novnc/noVNC/releases/tag/v1.2.0) added unicode copy&paste feature with https://github.com/novnc/noVNC/issues/61 . 
Could you please build image with this new version?

Thanks!

**Comment by realies** [comment]
Sounds great, thanks. Will add it in the next update.

Makes me wonder what would be a good way to track all dependencies and rebuild the image when they get updated.

**Comment by MattyBalaam** [comment]
At our company we use Dependabot to automatically raise PRs when dependencies update.
