### ISSUE TITLE
Cannot find config file for updating listening port

### ISSUE THREAD

**Issue by sirprancelot** [realies/soulseek-docker#35]
I am probably being very stupid here but I have spent hours looking around trying to work this out.  And I've reach the stage of now needing help.  I need to access the config file so I can use a script to update the port when used in conjunction with a VPN.  In a fork of this project the config file(s) are easily edited in /root/.nicotine/ whereas in this project which it is forked from... I just can't find the config file(s).  Can you give any pointers?  Many many thanks!

**Comment by realies** [comment]
@sirprancelot, from what you've written I'm not sure which port you'd like to configure. Soulseek's appdata is located at `/data/.SoulseekQt` and the port at which noVNC is exposed is configured through Docker.
