### ISSUE TITLE
Please describe the configuration process in detail

### ISSUE THREAD

**Issue by nafanz** [realies/soulseek-docker#4]
I am not familiar with Docker, so I have questions about setting up
Please add an explanation of the commands you specified in "Typical Usage"
I think it will be useful to other users

More specifically, how can I define my file paths?

`-v "/persistent/appdata":"/home/user/.SoulseekQt" \
-v "/persistent/logs":"/home/user/Soulseek Chat Logs" \
-v "/persistent/downloads":"/home/user/Soulseek Downloads" \`

I have the right train of thought?

How can I specify a folder that I want to open for other users?
As far as I understand, they don’t give me permission to go beyond the container through viewing files in the Soulseek. Files are in /home/user/music

**Comment by realies** [comment]
The `-v` parameter in Docker allows you to mount a volume or a folder to a container, more info on this is available in the docs. In the `Typical Usage` section `/persistent/` is the location on your host filesystem the you would share with the container, you would have a location for your Soulseek application data, saved chat logs (optional) and the Soulseek download location. The last might as well be your music collection folder (`/home/user/music`).

If I was you, I would also specify a location for Soulseek's application data on the host filesystem, so far the command would look like:

```
docker run -d --name soulseek --restart=always \
-v "/persistent/appdata":"/root/.SoulseekQt" \
-v "/persistent/logs":"/root/Soulseek Chat Logs" \
-v "/home/user/music":"/root/Soulseek Downloads" \
-e resolution=1280x720 \
-p 6080:6080 \
realies/soulseek
```
