### ISSUE TITLE
Support multiple passwords

### ISSUE THREAD

**Issue by realies** [realies/soulseek-docker#40]
Switching to TigerVNC and using multiple passwords seems to break mouse and keyboard input on any auth with a password other than the first one connecting to the server. Not sure if it's useful to have more than one password for authentication - I was not able to debug this. Any chance you have any ideas, @gordon00?

**Comment by gordon00** [comment]
I confirm that having multiple passwords is not very useful.
To grant multi user access to my soulseek-docker container, i used nginx as reverse proxy + ldap auth.
So I think u can revert the PR you've just merged ;)

**Comment by realies** [comment]
Changed the field to accept only one password with the most recent refactor. It was a surprise that passwords were trimmed at 8 characters at the server, but that's another topic... thanks for the contribution anyways! :)
