### ISSUE TITLE
Docker Image versioning

### ISSUE THREAD

**Issue by fkrivsky** [realies/soulseek-docker#41]
Hi,
would it be possible to version the images on Docker Hub, in addition to having the :latest tag rolling? 
Now there's no easy way to go back in case of issues.
Thanks!

**Comment by realies** [comment]
@fkrivsky, sorry if the latest update caused any issues! It changed all environment variables from lower caps to upper caps, in case it's related.

I was considering semantic versioning a couple of days ago, although decided it may be best to stick to :latest, as it usually brings security patches and usability improvements, except the latest breaking change. Promise not to have any of those going forward! Could you please share what's the particular use case to stick with an older version?

**Comment by fkrivsky** [comment]
Hi @realies , thanks for a prompt response!
I had issues with window not properly resizing initially but it's fine now...

Anyway, I'm not against the :latest tag. That should stay as is but you can keep the semantic versioning alongside as well.
There was a discussion about Selenium docker image versioning: https://github.com/SeleniumHQ/docker-selenium/issues/1365#issuecomment-914303042

**Comment by realies** [comment]
@fkrivsky, Soulseek versions aren't released that often. Updates here include security patches for the base image and improvements in the web interface stack, I'm not sure what use we would have by tagging and storing older images.

**Comment by fkrivsky** [comment]
I understand.
It's not a serious issue, it would be useful only if the image update broke something for someone.

**Comment by realies** [comment]
@fkrivsky, thanks for understanding. I know a recent update had a breaking change (environment variables got capitalised), for which I apologise. Future versions may only add optional parameters without breaking the functionality.
