### ISSUE TITLE
Docker port remains allocated over restarts

### ISSUE THREAD

**Issue by mixm1xmix** [realies/soulseek-docker#44]
I am running Docker on a Synology device and have noted that the soulseek container fails to start up when I reboot the Synology device - no other containers experience this issue.

Start container soulseek failed: {"message":"driver failed programming external connectivity on endpoint soulseek (4eb32cd080d2f5e7c6f57e38c75863c9ec8ded7dd3a7fb016dda3b88e0829216): Bind for 0.0.0.0:32805 failed: port is already allocated"}.

I am remapping 6080 to another available port. In this case, 32805 - I had previously set the config to use 32801, then 32802, etc. Each time, after a period of time when the soulseek docker would restart, it cannot start again as the configured port is in use.

When I check what might be using that port, it's just docker. No other containers are using this port. Unsure how the soulseek container might be allocating its port that causes this...

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:32805           0.0.0.0:*               LISTEN      20884/docker-proxy

**Comment by realies** [comment]
Try removing any old instances of the container if there's any. Otherwise, it might be a Docker bug for your host, I would look for more guidence through Docker's support channels.

**Comment by mixm1xmix** [comment]
Definitely no old instances running - I ran a docker cleanup to be sure. I'll escalate to Synology, thanks.
