### ISSUE TITLE
Any idea on how to use Soulseek with Gluten ?

### ISSUE THREAD

**Issue by tiritibambix** [realies/soulseek-docker#58]
Hi, I've been enjoying Soulseek-docker a lot lately and it is great but I realized I had ports issues. Let me explain what happens.

I'm running Soulseek through [Gluetun](https://github.com/qdm12/gluetun) as a VPN and AirVPN as a provider (which is supported by Gluetun). I've forwarded my Soulseek listening and obfuscated ports in AirVPN and checked they are open from there, which confirms my Gluetun config is working.

I keep getting ```Port xxxxx mapping failure, miniupnp error: -3```

I'm not sure what I am doing wrong, but I believe this has to do with my Soulseek config.

Can anyone help ?

**Comment by realies** [comment]
@tiritibambix, where do you see `Port xxxxx mapping failure, miniupnp error: -3`?

**Comment by tiritibambix** [comment]
> @tiritibambix, where do you see `Port xxxxx mapping failure, miniupnp error: -3`?

Soulseek > Diagnostics > Logs > Port Forwarding

Can't remember what I've been trying since my original post, but now my error is ```No device list found during discovery. miniupnp error code: 0```

**Comment by realies** [comment]
@tiritibambix, did you try disabling UPnP?

**Comment by tiritibambix** [comment]
I did found this solution a couple days after posting. Should've closed this issue before. Thanks for your answers.
