### ISSUE TITLE
noVNC password

### ISSUE THREAD

**Issue by krodelabestiole** [realies/soulseek-docker#6]
hi, thanks for the great tool, I have been struggling for a while with half abandoned museek+ daemon...

I wish to have soulseek running on a headless server and access it remotely.
I have soulseek-docker up and running great, and a reverse proxy setup using apache to access it with SSL.
However there is no password set on noVNC, so anyone knowing the url could access my soulseek instance.
Would it be possible to specify a noVNC password through an environment variable e.g. ?

**Comment by realies** [comment]
Setting a password on `x11vnc` via an environment variable is possible, although that would still leave the `soulseek` folders with open access. It might be better to authenticate via the reverse proxy server.

**Comment by krodelabestiole** [comment]
ok, I did it that way. Thanks for the advice.
