### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by openssl-rand** [realies/soulseek-docker#61]
`Login failed. Reported failure reason: socket error. Please change your login settings in the Options tab and try reconnecting`
My soulseek was working recently, however I recently moved to proxmox virtual environment. After that it has stopped working. I have disabled the firewall in proxmox. I have only published 6080:6080.

**Comment by realies** [comment]
It sounds like something needs to be fixed with your config. Unfortunately, I'm not familiar with Proxmox. Please, feel free to update this issue if you find anything new.
