### ISSUE TITLE
No space allowed in the mount path

### ISSUE THREAD

**Issue by feelthesea** [realies/soulseek-docker#62]
In the Volume config, in the Mount Path, when I enter "/data/Soulseek Downloads", it appears that no space is allowed in the path.

Would anyone please help me ? Thanks.

**Comment by feelthesea** [comment]
I use Synology Docker.

**Comment by realies** [comment]
Try wrapping it in quotes. Or change the folder you're mounting. Unfortunately, I'm not familiar with Synology Docker, but feel free to update this issue if you find anything that fixes it.

**Comment by feelthesea** [comment]
I've tried the quotes without success. Thank you for the reply.

**Comment by feelthesea** [comment]
After I enter "/data/Soulseek Downloads" with a space between soukseek and downloads, it says that the value that i entered "does not match the field".
