### ISSUE TITLE
Kanji font missing

### ISSUE THREAD

**Issue by ThatzOkay** [realies/soulseek-docker#63]
When i try to search using kanji characters they don't show up

![image](https://user-images.githubusercontent.com/6585530/210051350-aa595940-9c31-481b-b51a-f3e42bc98e75.png)

**Comment by realies** [comment]
Do you know which font can handle these?

**Comment by ThatzOkay** [comment]
i found fonts-wqy-zenhei but have not tested it yet.

**Comment by cproensa** [comment]
what i did is:
`apt install fonts-noto-cjk`
and japanese texts is showing ok now, and also, can enter in search and results are found.

to find which fonts are the defaults for a given language, i looked (in a standard ubuntu installation), in file:
`/usr/share/language-selector/data/pkg_depends`
for lines of type `fn:`

It would be nice to have the most common lang fonts installed by default in the docker image

**Comment by ThatzOkay** [comment]
yeah. Would love for this to be added to the base system.

**Comment by realies** [comment]
Thanks for the input, @ThatzOkay & @cproensa! https://github.com/realies/soulseek-docker/commit/2feb3c7064ab418691bf6a47dfbc0322880995ca now includes `fonts-noto-cjk`.
