### ISSUE TITLE
Docker container stopped unexpectedly

### ISSUE THREAD

**Issue by siperwrx** [realies/soulseek-docker#64]
Hi there,
I'm running Soulseek in Docker on my Synology and every day or so, I get the following error message:
**Docker container soulseek stopped unexpectedly. Go to Docker for more information.**

In the container log, I see this:
**INFO stopped: soulseek (terminated by SIGTERM)**

Any ideas how to prevent this?

**Comment by realies** [comment]
@siperwrx, the SIGTERM signal is a generic signal used to cause program termination. Something must be stopping the container. Are there any other logs anywhere?

**Comment by siperwrx** [comment]
No, that's all I could find.

**Comment by realies** [comment]
I would need more to be able to make any assumptions.
