### ISSUE TITLE
Pulling error no matching manifest?

### ISSUE THREAD

**Issue by deadrubberboy** [realies/soulseek-docker#65]
Hi

Trying to deploy via stacks in portainer. Have successfully in the past, but started getting novice errors so figured I would try again.

Now I'm getting an error that says NO matching manifest Linux arm? 

What am I doing wrong? Thanks!

My stack:

version: "2.1"
services:

  soulseek:
    image:
      realies/soulseek
    container_name: 
     soulseekstacked
    network_mode: "host"
    environment:
       - PUID=1000
       - PGID=1000
       - TZ=America/New_York
    volumes:
       - /Volumes/data/Docker/AppData/soulseekstacked:/config
       - /Volumes/data/data/directdownloads:/downloads
       - /Volumes/data/data/directdownloads:/music
    restart: unless-stopped
    security_opt:
       - seccomp:unconfined

**Comment by realies** [comment]
It appears that you are trying to pull an ARM version of the image, which does not exist. Unfortunately, Soulseek and this Docker image are only built for AMD64 platforms.

**Comment by deadrubberboy** [comment]
I am on an m1 Mac. It worked on this same machine before. How do I control the type of image I'm pulling?

**Comment by realies** [comment]
You could try to pre-pull the image before running Portainer with `docker pull --platform linux/amd64 realies/soulseek:latest`. I don't see an option to specify the image platform there.

**Comment by deadrubberboy** [comment]
progress! That got it to deploy! Thank you. Now I get the NOVNC page but it just has 3 dots scrolling right to left likes it is loading but never completes.

**Comment by deadrubberboy** [comment]
Disregard. I'm in! Seems I was impatient. :) Thank you so much!
