### ISSUE TITLE
Options->Login->uPnP

### ISSUE THREAD

**Issue by Corneloues** [realies/soulseek-docker#66]
I have UPnP port mapping enabled. When Slsk ran on a PC it would automatically update the router with the listening ports.

Since moving to this docker image, the router is not receiving the port details via uPnP.

**Comment by realies** [comment]
By default, Docker creates a separate network interface for containers, which can prevent uPnP from working correctly. You can try using the host network interface, by running the container with the `--net=host` option. You could also verify that the uPnP-enabled devices on the network can discover the application running inside the Docker container. This can be done using a uPnP discovery tool, such as upnpc or gupnp.
