### ISSUE TITLE
Options->Login->Check Ports

### ISSUE THREAD

**Issue by Corneloues** [realies/soulseek-docker#67]
Is it possible to launch a browser within the container so that the "Check Ports" button can function.

This has always been the best method to test if the router ports are configured correctly.

**Comment by realies** [comment]
Adding a full-fledged browser inside the container would make the Docker image significantly bigger for opening that one link. You can open it manually from the same network as the container, the link is http://tools.slsknet.org/porttest.php?port=59916 when your port configuration looks like this:
<img width="346" src="https://user-images.githubusercontent.com/5107843/220957902-260ee932-8b6e-4547-998a-9d62639fbf99.png">

**Comment by Corneloues** [comment]
This isn't possible as my router only opens the port to a specific device. So unless I can browse there from the unRaid server, the port will appear blocked.

I'm gonna have to lock solutions in community apps.

**Comment by realies** [comment]
@Corneloues, `curl http://tools.slsknet.org/porttest.php?port=59916` from the container.
