### ISSUE TITLE
VNC Access Failes

### ISSUE THREAD

**Issue by Corneloues** [realies/soulseek-docker#68]
Since the last update, I can no longer VNC into the app.

- TigerVNC: Reports the connection was "actively rejected".
- noVNC: The browser reports "ERR_CONNECTION_REFUSED"

I was happily using VNC Viewer on PC and Android, but even that doesn't connect now.

I've tried rebuilding to container - including deleting the local template and starting afresh from Advanced View.

Logs report it has started, but I cannot access.

> 2023-02-24 13:02:45,894 INFO Set uid to user 0 succeeded
> 2023-02-24 13:02:45,896 INFO supervisord started with pid 1
> 2023-02-24 13:02:46,899 INFO spawned: 'tigervnc' with pid 15
> 2023-02-24 13:02:46,900 INFO spawned: 'openbox' with pid 16
> 2023-02-24 13:02:46,902 INFO spawned: 'novnc' with pid 17
> 2023-02-24 13:02:46,904 INFO spawned: 'soulseek' with pid 18
> 2023-02-24 13:02:48,413 INFO success: tigervnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-02-24 13:02:48,413 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-02-24 13:02:48,413 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2023-02-24 13:02:48,413 INFO success: soulseek entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Are there any tests I can run from my end?

**Comment by realies** [comment]
I'm unable to replicate this. Does it happen if you spawn a new container? Did you try purging the browser cache or an incognito window?

**Comment by Corneloues** [comment]
Yes, all of that... As posted in the unraid forums, I'm still struggling

**Comment by realies** [comment]
> Yes, all of that... As posted in the unraid forums, I'm still struggling

I can't start fixing it without replicating.
