### ISSUE TITLE
Request VPN in container

### ISSUE THREAD

**Issue by screwfaze** [realies/soulseek-docker#7]
Feature request to add vpn to this like some Qbittorent docker images out there using openvpn and configuration file

**Comment by realies** [comment]
Would be better to use another container as the VPN connection and route anything that you would like to go through it by [reusing its network stack](https://docs.docker.com/engine/reference/run/#network-settings) instead of bloating minimal containers with additional features.

**Comment by screwfaze** [comment]
Ok didn't know you could do that still new to docker will give it a shot.

Thanks
