### ISSUE TITLE
Losing SoulseekQT's UI configuration on restart

### ISSUE THREAD

**Issue by hetzjagd** [realies/soulseek-docker#70]
I'm finding when I restart the Soulseek container or stop and start it that the configuration is lost and I have to login again, set my shared folders again and most importantly the listening port is randomized. Is the behavior different from the Windows client for Soulseek? The Windows client doesn't change the listening port on restart for me, which is handy given the need to manually open the port on my firewall.  I did see your mention of this in the readme.MD but I'm confused as to why it's the case as in my scenario it's stopping me being able to set this up as I need to know and specify the ports Soulseek will be using before I launch the container.  I can't do that if it's randomizing them after launch.  I'm in a loop mentally about it and possibly missing something obvious.

Also I couldn't figure out how to use Docker CLI or Compose to install your soulseek package, I just searched for it and downloaded it from the Registry tab in Docker and configured it using the GUI.

**Comment by realies** [comment]
Check #1.

**Comment by hetzjagd** [comment]
Ahh thank you for the IMMEDIATE reply first of all, that's incredible.  Also thank you for that, that answers my question.  I had checked the Issues tab but as I use github infrequently and am still getting caught up on very basic mistakes such as I didn't realize there was also the history of Closed issues available.
