### ISSUE TITLE
changing listening port

### ISSUE THREAD

**Issue by goffy59** [realies/soulseek-docker#71]
Alright so I use port forwarding on my vpn and that means I have to manually set the port inside soulseek for it to work. I could not find a restart option for the actual application within the container so the port change could proceed so I ended up logging into the container via /bin/bash and restarting the service (which i always forget how to do and google each and every time this is required because the port forwarding on PIA vpn is good for 60 days.)

Is there an option to restart the service (NOT THE CONTAINER ITSELF) because if you restart the container the listening port does not change to what I had set to match the PIA VPN port forward. Basically this is so I can make sure I am able to share with others so I am not just leeching. After getting the service inside the container to restart, the port you change it to will stay to whatever you set it to. I was hoping either explain where to restart the application itself within the container (not the container itself) or add this feature so people can change the listening port and restart(not the container) for effect.

thank you so much and thank you for your lovely work on this project. It is a must have for home lab and its built extremely well and is very stable. :)

**Comment by barelyelectric** [comment]
In Options, General the Save client data every x minutes - change that to a low number like 5min and change the listening port. Wait longer than that set amount of time and a container restart should retain changes. You can set it back to something reasonable afterwards.

**Comment by goffy59** [comment]
Thank you so much! :)
