### ISSUE TITLE
Unable to start after container update

### ISSUE THREAD

**Issue by VinneyUK** [realies/soulseek-docker#74]
<img width="1390" alt="Screenshot 2023-07-06 at 07 26 42" src="https://github.com/realies/soulseek-docker/assets/66467679/eb586e1a-1a41-4151-8452-17d218ff9376">

Any ideas?

**Comment by xerosys** [comment]
I'm getting the same exact problem.  It used to work fine and just started happening after update.

**Comment by VinneyUK** [comment]
I found a solution, wipe your cookies and it should fix it .....

**Comment by xerosys** [comment]
You're awesome. That worked for me too!

**Comment by realies** [comment]
It must have been a breaking change from the upstream noVNC package. Thanks for posting the fix.
