### ISSUE TITLE
Issues with spaces in volumes

### ISSUE THREAD

**Issue by indadb** [realies/soulseek-docker#77]
Using last docker container manager in Synology DSM 7.2 I am receiveing errors with next volumes due to spaces between words

-v /volume1/descargas/Soulseek Downloads:/data/Soulseek Downloads \
-v /volume1/docker/soulseek/logs:/data/Soulseek Chat Logs \
-v /volume2/music:/data/Soulseek Shared Folder \

Probably it´s because of the kernel but, can be fixed in any new update?

Thanks and regards
![eerror](https://github.com/realies/soulseek-docker/assets/104695714/6ae023c7-d83f-4ad4-a33c-0ac3d5ecd1e2)

**Comment by realies** [comment]
I don't have a Synology NAS to try this, but spaces in folder paths should work fine. You can mount any directory anywhere on the container filesystem and select it in Soulseek's settings.

**Comment by indadb** [comment]
The fact is that the issue happens with the path configured in docker settings, not in the folders I select...

I mean:

/volume1/descargas/Soulseek Downloads ---> it´s my local path and works fine 
/data/Soulseek Downloads ---> it´s the mount path and trigger an error (if i modify such as /data/Soulseek_Downloads it works.

It partially works but because I can modify download folder in Soulseek seetings but I can´t see how modify logs folder in soulseek gui seetings.

Thanks and regards

**Comment by realies** [comment]
@indadb, mount at `/usr/share/novnc/{downloads,shared,logs}` instead of `/data/{Soulseek Downloads, Soulseek Chat Logs, Soulseek Shared Folder}`.

**Comment by indadb** [comment]
It works!! thank you very much @realies I really aprecciate your work and support
