### ISSUE TITLE
supporting arm arch

### ISSUE THREAD

**Issue by goffy59** [realies/soulseek-docker#79]
I was curious how difficult it would be to make this work on raspberry pies and what not. I run most of my dockers on my rock pi 4b (6 core work horse). I have a special vm just for this docker. I was wondering if you ever thought of making it work for arm as well? If not no worries of course. Last I tried to build it for my arm it didn't work. Its been awhile but I want to simplify my homelab/servers. Other than that, the container works beautifully. I pair it up with gluetun.

**Comment by realies** [comment]
The Soulseek app does not support ARM. It can't be done without an ARM client unless it's emulated. You could check if any 3rd party clients support it.
