### ISSUE TITLE
On Synology host network, VNC prompts for authentication

### ISSUE THREAD

**Issue by technerdist** [realies/soulseek-docker#81]
I tend to have connectivity issues on the default bridge network on my Synology's Docker instance. Because of this, I like to put my containers on the host network. Well, unlike the bridge network, when I connect to the container on the host network, I get a prompt for authentication to NOVNC. I'm not sure of the password, or a password that would work in this context. Please assist me understand how to mitigate this issue.

**Comment by technerdist** [comment]
I just rebuilt my container with the NOVNC variable set to a password of my choosing, but I still get the same authentication failure. 

-e VNCPWD="pw" \

**Comment by realies** [comment]
could you test with a password that's at least 6 characters long?

**Comment by technerdist** [comment]
I used a password quite longer than 5 characters long.

**Comment by realies** [comment]
anything unusual in the logs?

**Comment by MrCee** [comment]
Are you using Reverse Proxy? If so add a web socket in Reverse Proxy >> Custom Headers >> Create Web Socket.
