### ISSUE TITLE
Configuration lost when container restarts

### ISSUE THREAD

**Issue by bennyevangelista** [realies/soulseek-docker#82]
Hi, I noticed that everytime I restart soulseek container, it loses its configuration. I correctly mapped .SoulseekQt folder on a persistent path on the host (and I can write it from the container), but Soulseek doesn't seem to be writing .dat files.
On the Windows client I saw that it updates configuration when I close the application, and maybe the container doesn't close properly when restarted, so it never persists configuration. Is there a workaround or I'm missing something?

**Comment by realies** [comment]
check the closed issues

**Comment by bennyevangelista** [comment]
...my fault, only checked the open ones :) Thanks!
