### ISSUE TITLE
On TrueNAS Scale i get chown permission denied

### ISSUE THREAD

**Issue by ThatzOkay** [realies/soulseek-docker#83]
When i try to use this docker image on my TrueNas Scale as like a custom-app i get the message.
chown: changing ownership of '/tmp/.Xauthority': Operation not permitted

**Comment by realies** [comment]
Is /tmp mounted in the container? What are the permissions of that folder?

**Comment by ThatzOkay** [comment]
no clue what the permissions are can't even access the container as it errors out immediately

**Comment by realies** [comment]
Do you still see the issue with the latest update, @ThatzOkay?

**Comment by ThatzOkay** [comment]
I'll check it out tommorow. I have now also changed back to truenas scale custom docker instead of truecharts custom docker which does work.

**Comment by realies** [comment]
@ThatzOkay is this still an issue?
