### ISSUE TITLE
Synology Docker (Container Manager) doesn’t accept spaces in paths

### ISSUE THREAD

**Issue by iAmRenzo** [realies/soulseek-docker#86]
Perhaps not really an issue, but for me it is. Container Manager on my Synology DSM 7 isn’t accepting spaces in path names. When I remove the spaces the folders aren’t filled (which makes sense). Everything works fine but files are probably stored inside the container which I don’t want. Is there any workaround?

**Comment by realies** [comment]
quotes, probably

**Comment by iAmRenzo** [comment]
<img width="217" alt="Scherm­afbeelding 2024-03-23 om 13 59 57" src="https://github.com/realies/soulseek-docker/assets/1183790/0eb24ff3-21a6-4084-a80d-8eb7c2cad212">
Not in the Container Manager...

**Comment by realies** [comment]
ask synology, i don't have any products from them and docker supports quotes

**Comment by Maypul** [comment]
@iAmRenzo I have docker on my Synology NAS but I do not use their UI as it's very limited - you can use CLI instead and run your docker that way, then it will accept space in the name. I run Soulseek via compose on my NAS and it works just fine.
