### ISSUE TITLE
VNC keeps disconnecting?

### ISSUE THREAD

**Issue by deadrubberboy** [realies/soulseek-docker#87]
Hi!

Been using this container for years without issue. Today it started acting weird. It connects, and as soon as I log into SLSK VNC disconnects and I end up in a loop back at the SLSK log in screen again. Same thing happens. I don't see any errors in the terminal log in Portainer/Dockge.

Any ideas why this started and how I can correct?

**Comment by realies** [comment]
try an incognito tab to check if there's any cache causing this

**Comment by realies** [comment]
i've updated the base image and have added a newer soulseek app build from https://groups.google.com/g/soulseek-discussion/c/E69FDwm1puw/m/FGOazKBoAAAJ; please give the latest image a go and let me know if there's any issues

**Comment by mixm1xmix** [comment]
Updated the image, recreated my container. It just continues to restart the container, never loads properly.

**Comment by deadrubberboy** [comment]
> I'm looking into fixing this, a temporary workaround should be running it as root.

Thanks for working on this!

Sorry for dumb question: how do we implement this work around? Not sure where to enter root credentials or what they are for the container.

**Comment by realies** [comment]
To run as root inside you should set PUID and PGID to 0.

You can replace the paths with a space inside with ones without a space. Those are just the default folders the Soulseek app uses, but they are configurable from its settings.

**Comment by mixm1xmix** [comment]
> To run as root inside you should set PUID and PGID to 0.
> 
> You can replace the paths with a space inside with ones without a space. Those are just the default folders the Soulseek app uses, but they are configurable from its settings.

Confirmed, PUID and PGID to 0 allowed this to run. Will monitor for a fix and redeploy. Thanks!

**Comment by realies** [comment]
Please try the latest build with your previous settings that didn't work. It's best not to run as PUID and PGID set to 0.

**Comment by mixm1xmix** [comment]
> Please try the latest build with your previous settings that didn't work. It's best not to run as PUID and PGID set to 0.

I believe I've patched the image, but it continues to restart with my PUID and PGID.

**Comment by realies** [comment]
Can you provide a log, @mixm1xmix?

**Comment by mixm1xmix** [comment]
> Can you provide a log, @mixm1xmix?

[soulseek.csv](https://github.com/realies/soulseek-docker/files/15213106/soulseek.csv)

**Comment by realies** [comment]
This is not the latest image, @mixm1xmix. Try stopping the container and deleting the image you have first.

**Comment by mixm1xmix** [comment]
Thanks - watchtower had not grabbed the latest update. Looks good,
appreciate all your help!

**Comment by deadrubberboy** [comment]
Works for me!
