### ISSUE TITLE
[Suggestion] VNCPWD to load as a secret

### ISSUE THREAD

**Issue by Maypul** [realies/soulseek-docker#89]
Hello,

is it something that could be implemeneted in the future? I'd like to have an option to load VNC password from a file using docker secrets.

As an exaple, in the compose, it could look like this:

  soulseek:
(.,..)
    secrets:
      - source: soulseek_vnc_password
        target: /run/secrets/soulseek_vnc_password
    environment:
      VNCPWD_FILE: /run/secrets/soulseek_vnc_password

Benefit with it is that, the password in not readable in the variables.

**Comment by realies** [comment]
Can you check if this works with the latest build, @Maypul?
