### ISSUE TITLE
Reverse Publish

### ISSUE THREAD

**Issue by yesluv** [realies/soulseek-docker#9]
Is there a way to change the web server home dir so we can reverse publishe via nginx for example

so that URL and links use http://<servernameorIP>:6080/soulseek rather than http://<servernameorIP>:6080

hope that makes sense
thanks

**Comment by realies** [comment]
You can modify the access endpoint within the Nginx configuration.

**Comment by yesluv** [comment]
thanks. I have managed to rewrite on nginx and also add support for ws. Only issue now is that search isnt working now. Also, config doesnt appear persistent and the /.SoulSeetQT folder is empty. Should there be a config file in there?

**Comment by realies** [comment]
Soulseek functionality is unrelated to Nginx routing. If the appdata folder is empty, try to save the config manually. Discussed at https://github.com/realies/soulseek-docker/issues/1.

**Comment by yesluv** [comment]
Awsome thanks that worked :) i now have persistent config. Now just to fix the search which isnt working now outside of nginx... prob something silly ive done somewhere

Great work by way. It seem this is the only decent attempt i have seen to allow web based access to soulseek

If anyone else is trying to reverse publish/proxy through nginx then this may help
Use the following to remove the URI used in nginx before sending to souseek webserver (add this to the server block, it assumes you have used /soulseek as the URI). Other lines add ws support for streaming
rewrite /soulseek(/.*) $1 break;
# WebSocket support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;

**Comment by yesluv** [comment]
I now have this working fine reversed published via NGINX (Organizr v2 iFrame Tab) with SSL and login support

Good work

**Comment by sharp004** [comment]
Hi yesluv,
I'm trying to reverse proxy soulseek with OrganizrV2 too, but unsuccessfully...
Can you please share your config ?
