### ISSUE TITLE
permissions of shared folder

### ISSUE THREAD

**Issue by mamema** [realies/soulseek-docker#91]
... are "chmod" every boot according to puid pgid settings.

why?

only solution is mounting read only, then the container log gets filled with:

chmod: changing permissions of '...': Read-only file system

should be avoided because it always triggers a large backup task here, as file is modified....
should be set via env var if needed

**Comment by realies** [comment]
this was added because people were having issues with mounting folders with unsuitable owner:group or permissions, I'm wondering what would be the best default behaviour

**Comment by mamema** [comment]
just make this an option to be disabled via env vars

**Comment by realies** [comment]
try setting MODIFY_VOLUMES to false
