### ISSUE TITLE
New issue since refreshing container 

### ISSUE THREAD

**Issue by VinneyUK** [realies/soulseek-docker#93]
Can someone help me understand why I am all of a sudden getting this error please?

`
s6-rc: info: service svc-openbox: starting
s6-rc: info: service svc-novnc: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service svc-tigervnc successfully started
s6-rc: info: service svc-openbox successfully started
s6-rc: info: service svc-soulseek successfully started
s6-rc: info: service svc-novnc successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-setup: starting
Xvnc TigerVNC 1.13.1 - built 2024-04-01 08:26
Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12101011
Tue Jun 11 19:26:01 2024
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5900
 vncext:      created VNC server for screen 0
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
Warning: could not find self.pem
Using local websockify at /usr/share/novnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
`

**Comment by realies** [comment]
@VinneyUK, how do you start the container?

**Comment by VinneyUK** [comment]
its within a stack in portainer.

**Comment by realies** [comment]
To be able to help, I need to reproduce your issue. How does Portainer start the container?

**Comment by VinneyUK** [comment]
version: "3"
networks:
 mystack-vpn_default:
   ipam:
    driver: default 
    config:
     - subnet: 172.28.0.0/16
  
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks: 
     mystack-vpn_default:
      ipv4_address: 172.28.0.2
    ports:
      - 8000:8000/tcp # Gluetun
      - 9000:9000 # theLounge
      - 113:9001 # theLounge
      - 9696:9696/tcp # prowlarr

      - 8282:8282/tcp # SABnzbd
      - 13000:3000 # filezilla
      - 55896:55896 #soulseek
      - 55897:55897 #soulseek
      - 2416:2416   #soulseek
      - 6080:6080   #soulseek 
      - 8181:8181    #qBitorrent 
      - 6881:6881     #qBitorrent
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /home/dietpi/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORTFORWARDING=ON
      - VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port
      - FIREWALL_OUTBOUND_SUBNETS=172.28.0.0/16,192.168.50.0/24
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/dietpi/prowlarr:/config
  # ports:
  #   - 9696:9696
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/dietpi/sabnzbd:/config
      - /mnt/shared2/downloads/:/downloads #optional
      - /mnt/shared2/downloads/tmp/incomplete:/incomplete-downloads #optional
      - /mnt/shared2/downloads/tmp/watch:/watch #optional
  # ports:
  #   - 8282:8282
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
      
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    # ports:
    # - 113:9001
    # - 9000:9000
    volumes:
       - /home/dietpi/thelounge:/var/opt/thelounge
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn

  soulseek:
    image: realies/soulseek
    container_name: soulseek
    security_opt:
      - seccomp:unconfined
    volumes:
      - '/home/dietpi/soulseek/appdata:/data/.SoulseekQt'
      - '/mnt/shared2/Downloads/unsorted:/data/Downloads:rw'
      - '/home/dietpi/soulseek/logs:/data/Soulseek Chat Logs'
      - '/mnt/shared/Lossy Music:/data/Lossy'
      - '/mnt/shared/Packs:/data/Packs'
      - '/mnt/shared/Rare Acapellas:/data/Rare Acapellas'
      - '/mnt/shared2/Lossless Music:/data/Lossless'
      - '/mnt/shared/Exclusive:/data/Exclusive'
    environment:
      - UMASK=022
      - PGID=0
      - PUID=0
    network_mode: service:vpn
    depends_on:
      - vpn

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK=022
      - WEBUI_PORT=8181
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - /home/dietpi/qbittorrent:/config
      - /mnt/shared2/downloads/unsorted:/downloads #optional
      - /mnt/shared2/downloads/tmp/incomplete:/incomplete-downloads #optional
      - /mnt/shared2/downloads/tmp/watch:/watch #optional
  # ports:
  #   - 8181:8181
  #   - 6881:6881
  #   - 6881:6881/udp
    labels:
      - autoheal=true
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    network_mode: service:vpn
    depends_on:
      - vpn

**Comment by VinneyUK** [comment]
@realies does that help?

**Comment by VinneyUK** [comment]
@realies let me investigate further when I have time, and will get back to you. Thank you.,

**Comment by VinneyUK** [comment]
@realies can I rollback to a earlier version?

**Comment by realies** [comment]
You can check out this repository at an earlier commit and build an image from it. Probably better to debug what's going wrong if it does not work. Are you sure it does not work?
