### ISSUE TITLE
high CPU usage - UNRAID

### ISSUE THREAD

**Issue by VinneyUK** [realies/soulseek-docker#95]
Hi,
I've moved to UNRAID and experiencing high cpu usage. 

When I look at logs, I see highly active errors repeating:

Any advice, please?

<img width="1657" alt="Screenshot 2024-07-20 at 23 29 21" src="https://github.com/user-attachments/assets/effa15da-4336-4f20-8b99-99a2e94193e4">

**Comment by realies** [comment]
it looks like it tries to analyse your library, and some of the files can't be read by the taglib library; i assume it will quiet down once it goes through all files; this is some soulseek-client specific functionality, you can ask in their community if it continues
