### ISSUE TITLE
how do I change the default noVNC port of 5901

### ISSUE THREAD

**Issue by VinneyUK** [realies/soulseek-docker#96]
Hi 
Im trying to full this with a docker of FileZilla, look like both can't be run at the same time due to both sharing port 5901.

Can you tell me how I go about changing it please???

**Comment by realies** [comment]
Don't use network: host and map it to a different port.

**Comment by VinneyUK** [comment]
I can’t do that. I’ve mapped it into a VPN container, hence I have the conflict between it and FileZilla which are both going through the VPN container.

**Comment by VinneyUK** [comment]
I

**Comment by realies** [comment]
There's now a VNC_PORT environment variable.
